neustartklima/ich-kann-klima

.gitignore, Slider.js, index.html, package-lock.json, package.json, script.js, styles.css, test/Slider.spec.js
The script was way too large, so I create a separate Slider module to encapsulate this functionality.
=> Refactored slider

frontend/src/Factory.ts, frontend/src/laws/EnergiemixDurchMarktGeregelt.ts, frontend/src/laws/InitialAtomausstieg.ts, frontend/src/laws/KeineFoerderungFuerTierhaltung.ts, frontend/src/laws/KernenergieVerlaengern.ts, frontend/src/laws/Kohleverstromung.ts, frontend/src/laws/WindenergieSubventionieren.ts, frontend/src/types.ts, frontend/tests/Calculator.spec.ts, frontend/tests/LawProposer.spec.ts
Das ist ja recht einfach. Ein wenig unschön: Die ID ist im Grund immer gleich dem Dateinamen. Siehst Du eine Möglichkeit, den Dateinamen als ID zu verwenden?
=> Adding Filename as ID to Law.

frontend/src/LawProposer.ts, frontend/src/laws/EnergiemixDurchMarktGeregelt.ts, frontend/src/laws/InitialAtomausstieg.ts, frontend/src/laws/KeineFoerderungFuerTierhaltung.ts, frontend/src/laws/KernenergieVerlaengern.ts, frontend/src/laws/Kohleverstromung.ts, frontend/src/laws/WindenergieSubventionieren.ts, frontend/src/types.ts, frontend/tests/Calculator.spec.ts, frontend/tests/LawProposer.spec.ts
Bin noch unsicher, ob die wirklich optional sein sollte. Außer bei "hidden" und/oder "initial" ist das eigentlich nicht so sinnvoll, oder? Und bei denen kann man ja einfach `return 0` machen.
=> New optional priority function for Laws.

src/App.vue, src/components/CurrentIndicators.vue, src/components/EventOccurred.vue, src/components/GameSetup.vue, src/components/Indicator.vue, src/components/LawProposals.vue, src/components/TimeIndicator.vue, src/views/GamePage.vue
=> New design with time indicator as background

src/EventMachine.ts, src/events/Finanzkollaps.ts, src/events/Hitzehölle.ts, src/events/TimesUp.ts, src/events/WahlVerloren.ts, src/events/index.ts, src/repository.ts, src/router.ts, src/store/actions.ts, src/store/mutations.ts, src/types.ts, src/views/GameOver.vue, src/views/GamePage.vue, src/views/StartPage.vue, tests/Calculator.spec.ts, tests/EventMachine.spec.ts
=> End of game

src/components/CurrentIndicators.vue
=> Removing scrollbar on wide screens.

src/views/GameOver.vue
=> Print results on GameOver page

src/components/Indicator.vue
=> Only top most circle in indicators contains an icon

.vscode/settings.json, src/components/PeekInside.vue, src/components/PeekTools.ts, tests/PeekTools.spec.ts
=> #38 peek mode enhancements

src/Factory.ts, src/LawProposer.ts, src/events/Finanzkollaps.ts, src/events/Hitzehölle.ts, src/events/SocialMedia.ts, src/events/TimesUp.ts, src/events/WahlVerloren.ts, src/events/bestechung.ts, src/events/index.ts, src/laws/DaemmungVonWohngebaeudenFoerdern.ts, src/laws/EnergiemixRegeltDerMarkt.ts, src/laws/FoerderungFuerTierhaltungAbschaffen.ts, src/laws/InitialAtomausstieg.ts, src/laws/KernenergienutzungVerlaengern.ts, src/laws/KohleverstromungEinstellen.ts, src/laws/NahverkehrAusbauen.ts, src/laws/NahverkehrKostenlos.ts, src/laws/WindenergieSubventionieren.ts, src/laws/index.ts, src/types.ts, tests/Calculator.spec.ts, tests/LawProposer.spec.ts
With this PR events and laws both have unique ids automatically.
=> Unified laws and events

.vscode/launch.json, .vscode/settings.json, package-lock.json, package.json, tests/EventMachine.spec.ts, tests/PeekTools.spec.ts, tsconfig.json
Not sure about this one, at all.
=> Tests via mocha for vscode test explorer and debugging.

src/EventMachine.ts, tests/EventMachine.spec.ts
=> Use fisher-yates algorithm for a random _permutation_ instead of actual (pseudo) randomness in tests

src/Calculator.ts, src/components/PeekTools.ts, src/events/Finanzkollaps.ts, src/laws/EnergiemixRegeltDerMarkt.ts, src/laws/KernenergienutzungVerlaengern.ts, src/model/Repository.ts, src/model/api.ts, src/model/index.ts, src/store/actions.ts, tests/Calculator.spec.ts, tests/EventMachine.spec.ts, tests/LawProposer.spec.ts, tests/Laws.spec.ts, tests/PeekTools.spec.ts, tests/repository.spec.ts
Ich habe das Repository in ein eigenes Verzeichnis geschoben, um etwas aufzuräumen.
=> Moved repository into separate folder

src/LawProposer.ts, src/components/LawProposals.vue, src/constants.ts, src/laws/Tempolimit130AufAutobahnen.ts, src/store/actions.ts, src/views/GamePage.vue, tests/LawProposer.spec.ts
The actual fix of #60 is still missing, but the animation stuff might be woth a look.
=> #60 fix law proposer

src/EventMachine.ts, src/components/GameSetup.vue
This PR adds a list of possible next events with their priorities in the lower left of the screen, if dev mode is turned on.
=> View prioritized events in dev mode

src/App.vue, src/components/Background.vue, src/components/Dialog.vue, src/components/GameSetup.vue, src/views/GameOver.vue, src/views/MainPage.vue, src/views/StartPage.vue
Dachte mir, man sollte von Anfang an ein hübsches Layout der Anwendung haben.
=> Consistent layout

.vscode/extensions.json, src/citations/index.ts, src/components/Citation.vue, src/components/GameSetup.vue, src/components/PeekInside.vue, src/laws/AbschaffungDerMineraloelsteuer.ts, src/params/Params.ts, src/params/ParamsTypes.ts
Contents of Events and Props are still not shown.
=> Contents in Peek - Laws

package-lock.json, package.json
We already serve static data from dist folder, so it is sufficient to copy or source information files there.
You can use `npm run copy-sources` to to that, This step is included in `npm run build`, so that these files now are included in the docker file as well and can therefore be downloaded from https://ich-kann-klima.de/sources/
=> Copy information sources to dist folder

src/components/AcceptedLaws.vue, src/components/PeekInside.vue, src/model/Repository.ts, src/store/actions.ts, src/store/getters.ts, src/store/state.ts
I wanted to try, if `allLaws` are needed in the vuex state. They are not.
Is there any reason to keep them there? If so, shouldn't events go there, as well?
=> Remove unused vuex state.

documents/happyPath.drawio.svg, src/App.vue, src/citations/index.ts, src/laws/AbstandsregelnFuerWindkraftLockern.ts, src/laws/AusschreibungsverfahrenfuerWindkraftVervierfachen.ts, src/laws/DaemmungAltbau4Percent.ts, src/laws/DienstwagenPrivilegAbgeschaffen.ts, src/laws/KohleverstromungEinstellen.ts, src/laws/NahverkehrAusbauen.ts, src/laws/NahverkehrKostenlos.ts
I would like to continue in this way. Please tell me, if it is a waste of time or you'd do things differently.
=> Happy path

src/laws/AbschaffungDerMineraloelsteuer.ts, src/laws/AusbauVonStrassen.ts, src/laws/AutosInInnenstaedtenVerbieten.ts, src/laws/CO2PreisErhoehen.ts, src/laws/DienstwagenPrivilegAbgeschaffen.ts, src/laws/FernverkehrModernisieren.ts, src/laws/FernverkehrVerbindungenAusbauen.ts, src/laws/NahverkehrAusbauen.ts, src/laws/NahverkehrKostenlos.ts, src/laws/NahverkehrModernisieren.ts, src/laws/VollerCO2Preis.ts, src/laws/WirksamerCO2Preis.ts, src/params/index.ts, tests/Params.spec.ts
That complicated stuff always bugged me. Now it is much easier to transfer some amount from one parameter to another.
=> `transfer` convenience function.

.vscode/settings.json, package-lock.json, package.json, src/components/LawProposals.vue, src/events/NewYear.ts, src/game.ts, src/model/Repository.ts, src/model/api.ts, src/store/actions.ts, tests/Calculator.spec.ts
Hey Joachim,
before this change it took far too long to finish a year. This was, because it was done by counting the laws accepted in a year. However, events and other laws may un-accept already accepted laws. Therefore, we need the independent counter. 
With this change, the "Aussitzen" button was simple - at least this ugly one.
If we decide not to have it in the game, we can always hide it - as we did with the "reject" buttons of the laws.
closes #111
=> Progress counter and sit-out Button.

src/Calculator.ts, src/components/PeekChart.vue, src/components/PeekInside.vue, src/components/PeekTools.ts, src/laws/Test.ts, src/laws/index.ts, src/main.ts, src/params/index.ts, tests/PeekTools.spec.ts
=> #150 and #151: Effects of selected law in selected year.

src/components/Menu.vue, src/components/PeekInside.vue, src/components/PeekSimulator.ts
=> Compare simulations.

cypress/integration/GameOver.spec.js, src/components/LawProposals.vue
=> Put laws back on table with second click. Closes #182. Closes #118.

.vscode/extensions.json, .vscode/settings.json, cypress/integration/GameOver.spec.js, cypress/integration/GameStart.spec.js, package-lock.json, src/App.vue, src/components/GameSetup.vue, src/router.ts, src/views/StartPage.vue
=> Start page
